### ISSUE TITLE
RuntimeError: CUDA error: out of memory | OPT-1.3b | RTX 3090

### ISSUE THREAD

**Issue by genesst** [FMInference/FlexGen#44]
It seems that I am encountering several issues while attempting to run the smallest model. I would greatly appreciate it if someone could assist me in debugging this problem. 

Setup: RTX 3090 24GB, WSL2

After running `python -m flexgen.flex_opt --model facebook/opt-1.3b` I'm getting the following output:
```
I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
model size: 2.443 GB, cache size: 0.398 GB, hidden size (prefill): 0.008 GB
warmup - init weights
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/user/anaconda3/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/Developer/FlexGen/flexgen/pytorch_backend.py", line 881, in copy_worker_func
    cpu_buf = torch.empty((1 * GB,), dtype=torch.float16, pin_memory=True)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/user/anaconda3/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/Developer/FlexGen/flexgen/pytorch_backend.py", line 881, in copy_worker_func
    cpu_buf = torch.empty((1 * GB,), dtype=torch.float16, pin_memory=True)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/user/anaconda3/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/Developer/FlexGen/flexgen/pytorch_backend.py", line 881, in copy_worker_func
    cpu_buf = torch.empty((1 * GB,), dtype=torch.float16, pin_memory=True)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/user/anaconda3/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/Developer/FlexGen/flexgen/pytorch_backend.py", line 881, in copy_worker_func
    cpu_buf = torch.empty((1 * GB,), dtype=torch.float16, pin_memory=True)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
warmup - generate
benchmark - generate
benchmark - delete weights
```

It stops there ^^^

**Comment by min-xu-ai** [comment]
it could be the CPU memory that is running out? can you check your memory using something like `top`?

**Comment by genesst** [comment]
> it could be the CPU memory that is running out? can you check your memory using something like `top`?

```
top - 13:17:03 up  7:59,  0 users,  load average: 0.00, 0.10, 0.13
Tasks:  75 total,   1 running,  74 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.1 us,  0.0 sy,  0.0 ni, 99.9 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :  32002.9 total,   1498.1 free,   9429.5 used,  21075.3 buff/cache
MiB Swap:   8192.0 total,   8191.0 free,      1.0 used.  22123.1 avail Mem
```

Just noticed WSL is only assigned 32gb, but the system ram is 64gb

**Comment by min-xu-ai** [comment]
I ran opt-6.7b yesterday on my 64GB system with 3090 without any problems. Maybe you should try increase your wsl memory. I am still surprised that 32GB is not enough for 1.3b though.

**Comment by genesst** [comment]
I'll close this issue. Messed up the models. It'd run 1.3b perfectly fine, though I'm getting different errors now with 6.7b.
