### ISSUE TITLE
rtx3090 cublasGemmStridedBatchedExFix CUBLAS_STATUS_NOT_SUPPORTED 

### ISSUE THREAD

**Issue by ningpengtao-coder** [FMInference/FlexGen#57]
(flexgen) [ai@k3s4-worker FlexGen]$ python3 -m flexgen.flex_opt --model facebook/opt-1.3b
model size: 2.443 GB, cache size: 0.398 GB, hidden size (prefill): 0.008 GB
warmup - init weights
warmup - generate
Traceback (most recent call last):
  File "/home/miniconda3/envs/flexgen/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/miniconda3/envs/flexgen/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ai/FlexGen/flexgen/flex_opt.py", line 1307, in <module>
    run_flexgen(args)
  File "/home/ai/FlexGen/flexgen/flex_opt.py", line 1201, in run_flexgen
    output_ids = model.generate(
  File "/home/ai/FlexGen/flexgen/flex_opt.py", line 873, in generate
    self.generation_loop_overlap_single_batch()
  File "/home/ai/FlexGen/flexgen/flex_opt.py", line 1010, in generation_loop_overlap_single_batch
    self.compute_layer(i, j, 0)
  File "/home/ai/FlexGen/flexgen/flex_opt.py", line 776, in compute_layer
    self.layers[j].forward(self.hidden[i][j][k], self.cache_read_buf[j][k],
  File "/home/ai/FlexGen/flexgen/flex_opt.py", line 446, in forward
    h, new_k_cache, new_v_cache = self.compute.mha(h, mask, w_q, b_q,
  File "/home/ai/FlexGen/flexgen/pytorch_backend.py", line 330, in mha
    attn_weights = torch.bmm(q, k)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasGemmStridedBatchedExFix( handle, opa, opb, m, n, k, (void*)(&falpha), a, CUDA_R_16F, lda, stridea, b, CUDA_R_16F, ldb, strideb, (void*)(&fbeta), c, CUDA_R_16F, ldc, stridec, num_batches, CUDA_R_32F, CUBLAS_GEMM_DEFAULT_TENSOR_OP)`

**Comment by Ying1123** [comment]
Could you try to install the pytorch version that matches your cuda version?
