### ISSUE TITLE
ValueError: Invalid model name: galactica-30b

### ISSUE THREAD

**Issue by vmajor** [FMInference/FlexGen#99]
how do I pass the argument so that facebook/galactica-30b is loaded?

This generates the error in the title: `python -m flexgen.flex_opt --model facebook/galactica-30b --gpu-batch-size 32 --percent 100 0 100 0 100 0`

```
line 118, in get_opt_config
    raise ValueError(f"Invalid model name: {name}")
ValueError: Invalid model name: galactica-30b
```

Also, knowing what other arguments to pass in order to optimally run this model with flexgen would also be good.

**Comment by virtualramblas** [comment]
Same error trying with the facebook/galactica-1.3b:
````
Downloading (…)cial_tokens_map.json: 100% 221/221 [00:00<00:00, 1.32MB/s]
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/flexgen/flex_opt.py", line 1323, in <module>
    run_flexgen(args)
  File "/usr/local/lib/python3.10/dist-packages/flexgen/flex_opt.py", line 1207, in run_flexgen
    opt_config = get_opt_config(args.model)
  File "/usr/local/lib/python3.10/dist-packages/flexgen/opt_config.py", line 118, in get_opt_config
    raise ValueError(f"Invalid model name: {name}")
ValueError: Invalid model name: galactica-1.3b
````
